### ISSUE TITLE
Responsive support

### ISSUE THREAD

**Issue by salvatorecapolupo** [pistacchio/Dedalus#12]
Hello, 

is there any responsive theme i.e Bootstrap like? I'm trying themes on my browser and none seem responsive-friendly. What would be the best approach for this issue?

**Comment by pistacchio** [comment]
Hi,
no, Dedalus web has not being conceived to be responsive or to be used on a mobile. The engine, however, is split in a "core" part and a "web" part, where most of the work is done by the core part.

This would allow anyone to write a presentation layer that is alternative to the current "web" layer. One that works for mobile browsers could be an example of alternative presentation layer.

**Comment by salvatorecapolupo** [comment]
Hi,

so I could try submit new one mobile theme, someday. Just some time for testing :-)
